feat: add controllers, services, in memory storages for item and user
iluxa-152436/java-shareit pull request #1
Opened 2023-06-28 20:45 UTC by iluxa-152436

2023-06-29 19:49 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе, жду новую версию.

2023-06-29 19:49 UTC, Frilock commented on pom.xml
> +		<org.modelmapper.version>3.1.0</org.modelmapper.version>
org в название можно не добавлять, главное чтоб вам понятно было что за библиотека

2023-06-29 19:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item add(@RequestBody @Valid ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") long userId) {
Литерал X-Sharer-User-Id повторяется более 2х раз, вынесите его в константу класса

2023-06-29 19:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        Item oldItem = itemService.getItemById(itemId);
Лучше бы эту логику в сервис перенести, хотя в целом и такой вариант допустим, но я лично к первому склоняюсь

2023-06-29 19:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        if (text.isEmpty()) {
А null прийти не может? Тогда NPE получите. В таких случаях лучше проверять через StringUtils.isBlank

2023-06-29 19:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemMapper.java
> +        if (patchItemDto.getDescription() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-06-29 19:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public Item(Item item) {
А в чем смысл данного конструктора?

2023-06-29 19:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
А тут разве не NotEmpty подходит? https://struchkov.dev/blog/ru/spring-boot-validation/

Рассмотрим самые популярные ограничения:

@NotNull - аннотированный элемент не должен быть null. Принимает любой тип.
@Null - аннотированный элемент должен быть null. Принимает любой тип.
@NotBlank - аннотированный элемент не должен быть null и должен содержать хотя бы один непробельный символ. Принимает CharSequence.
@NotEmpty - аннотированный элемент не должен быть null или пустым. Поддерживаемые типы:

2023-06-29 19:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private static void checkItemOwner(Item newItem, long ownerId) {
Приватные методы принято писать ниже публичных

2023-06-29 19:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorageImpl.java
> +    private final Map<Long, Item> items;
А почему не инициализируете?

2023-06-29 19:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorageImpl.java
> +                .filter(item -> item.getDescription().toLowerCase().contains(text.toLowerCase())
Лучше воспользоваться StringUtils.containIgnoreCase

2023-06-29 19:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/controller/UserExceptionHandlerController.java
> +public class UserExceptionHandlerController {
Не уверен насчет такого решения с Handlerами для контроллеров. Вы для каждого контроллера будете делать свой обработчик ошибок? Нельзя ли обойтись 1м общим обработчиком? Ведь большинство ошибок похожи

2023-06-30 17:12 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public Item(Item item) {
Использую для копирования объекта.

2023-06-30 17:20 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
Кажется, что эти аннотации не работают с boolean или Boolean.

2023-06-30 17:29 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorageImpl.java
> +    private final Map<Long, Item> items;
поправил

2023-06-30 17:43 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/user/controller/UserExceptionHandlerController.java
> +public class UserExceptionHandlerController {
перенес в один класс

2023-06-30 17:56 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/item/controller/ItemMapper.java
> +        if (patchItemDto.getDescription() != null) {
Согласен. Поменял

2023-06-30 18:38 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        Item oldItem = itemService.getItemById(itemId);
Перенес логику в сервис. Честно говоря, пролистав теорию посчитал, что DTO больше про слой контроллера, а в сервисе работать с моделями. )))

2023-07-01 14:04 UTC, Frilock approved these changes
Принято

2023-07-01 14:04 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String USERID = "X-Sharer-User-Id";
USER_ID

2023-07-02 15:20 UTC, merged