Add bookings
iluxa-152436/java-shareit pull request #2
Opened 2023-07-19 20:31 UTC by iluxa-152436

2023-07-20 05:25 UTC, Frilock requested changes
Добрый день, в целом все нормально, указал ряд небольших комментариев, жду новую версию.

2023-07-20 05:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    public static Booking toEntity(BookingDto bookingDto, User creator, Item item) {
Если вы делаете класс бином, то достаточно методы сделать просто публичными. Статичными не надо их делать

2023-07-20 05:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
Добавьте транзакцию над рядом методов

2023-07-20 05:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            if (booking.getState().equals(BookingState.WAITING)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2023-07-20 05:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingStateFilter.java
> +    REJECTED;
; не нужна в конце, вам IDEA ее серой подсвечивает

2023-07-20 05:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +    @Query("select bo " +
а зачем Query над рядом методов? Вроде и так укладываетесь в названии запроса сам запрос

2023-07-20 05:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +    public static Comment toEntity(CommentPostDto commentPostDto, User user, Item item) {
Аналогично

2023-07-20 05:25 UTC, Frilock commented on src/main/resources/schema.sql
> +  state VARCHAR(10) NOT NULL,
Размеры полей которые вы указываете в скрипте, нужно также указать в поле lenght аннотации Column в ваших классах моделей, это нужно для того, чтобы лишний раз не лазить в скрипты, чтобы узнать размерность

2023-07-20 05:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @ManyToOne//(fetch = FetchType.LAZY)
Закоментированный код надо убрать

2023-07-20 12:41 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    public static Booking toEntity(BookingDto bookingDto, User creator, Item item) {
Убрал @Component, пока лишнее, т.к. нет необходимости внедрять как зависимость

2023-07-20 12:49 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            if (booking.getState().equals(BookingState.WAITING)) {
поправил

2023-07-20 12:49 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/booking/service/BookingStateFilter.java
> +    REJECTED;
поправил

2023-07-20 12:59 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @ManyToOne//(fetch = FetchType.LAZY)
поправил

2023-07-20 12:59 UTC, iluxa-152436 commented on src/main/resources/schema.sql
> +  state VARCHAR(10) NOT NULL,
добавил

2023-07-20 13:34 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +    @Query("select bo " +
Согласен, поправил

2023-07-20 14:42 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
Добавил

2023-07-21 07:08 UTC, Frilock approved these changes
Принято

2023-07-29 13:46 UTC, merged