Add item requests
iluxa-152436/java-shareit pull request #3
Opened 2023-08-02 22:06 UTC by iluxa-152436

2023-08-03 19:35 UTC, Frilock requested changes
Добрый вечер, работу посмотрел, комментарии оставил

2023-08-03 19:35 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from.isPresent() && size.isPresent()) {
Метод выглядит довольно громоздко, попробуйте его переработать. У вас же по сути меняется только запрос, поэтому просто проверяйте объект pageable и в зависимости от него внутри case делайте тот или иной запрос.
Кроме того, в блоке default кажется что лучше бросать исключение, поскольку это внештатная ситуация

2023-08-03 19:35 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            return PageRequest.of(from / size, size);
Съехало форматирование

2023-08-03 19:35 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +    List<Booking> findByItemUserIdAndStartAfterOrderByStartDesc(long ownerId,
В методах где вы работаете с объектом Pageable, логичнее возвращать не коллекцию, а объект Page

2023-08-03 19:35 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    BookingService service;
Модификаторы

2023-08-03 19:35 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    void add() throws Exception {
Предлагаю добавлять Test в конце к наименованию теста)

2023-08-03 19:35 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    BookingServiceImpl service;
Модификатор, кроме того лучше инжектить интерфейс

2023-08-03 19:35 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +
Лишняя пустая строка

2023-08-04 09:43 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            return PageRequest.of(from / size, size);
поправил

2023-08-04 09:46 UTC, iluxa-152436 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    BookingService service;
поправил

2023-08-04 09:50 UTC, iluxa-152436 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    void add() throws Exception {
ок

2023-08-04 09:52 UTC, iluxa-152436 commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    BookingServiceImpl service;
поправил

2023-08-04 09:53 UTC, iluxa-152436 commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +
поправил

2023-08-04 13:38 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from.isPresent() && size.isPresent()) {
понял, переделал

2023-08-04 15:45 UTC, iluxa-152436 commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +    List<Booking> findByItemUserIdAndStartAfterOrderByStartDesc(long ownerId,
поправил на тип возвращаемого значения  Page

2023-08-04 20:59 UTC, Frilock approved these changes
Принято, хорошо

2023-08-04 20:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> -@RequiredArgsConstructor
А почему убираете?

2023-08-05 10:15 UTC, merged